import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

// GitHub Pages allows no HTTP headers, so the CSP ships as a meta tag injected
// at build time only (the Vite dev server relies on inline scripts). blob: is
// required for export and media preview, data: for the favicon and thumbnails,
// 'unsafe-inline' in style for framer-motion.
// 'wasm-unsafe-eval' is what lets ffmpeg.wasm compile its module: it is the
// narrow WebAssembly-only permission, and does NOT re-enable eval() for scripts.
// The core is served from our own origin (copied out of node_modules at build
// time by copyFFmpegCore), so no CDN needs allowing.
const CSP = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval' blob:",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' blob: data:",
  "media-src 'self' blob:",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

function injectCsp(): Plugin {
  return {
    name: 'inject-csp',
    apply: 'build',
    transformIndexHtml(html) {
      return {
        html,
        tags: [
          {
            tag: 'meta',
            attrs: { 'http-equiv': 'Content-Security-Policy', content: CSP },
            injectTo: 'head-prepend',
          },
        ],
      };
    },
  };
}

/**
 * Serve ffmpeg.wasm's core from our own origin at /ffmpeg/.
 *
 * The core is 32 MB, so it is copied straight out of node_modules rather than
 * committed to the repo or pushed through rollup's asset pipeline. Nothing
 * requests it until the user asks to transcode an undecodable audio track, so
 * it never weighs on a normal page load.
 */
function copyFFmpegCore(): Plugin {
  // The ESM build, not the UMD one. ffmpeg.wasm spawns its worker with
  // `type: 'module'`, where importScripts() does not exist: its loader falls back
  // to `import(coreURL)` and reads `.default`, which a UMD bundle does not have.
  // Pointing at UMD makes load() fail with "failed to import ffmpeg-core.js".
  // require.resolve picks the "require" condition (UMD), so cross over by hand;
  // the package exports no './package.json' to resolve against directly.
  const coreDir = path.join(path.dirname(require.resolve('@ffmpeg/core')), '..', 'esm');
  const files = ['ffmpeg-core.js', 'ffmpeg-core.wasm'];
  const sourceOf = (name: string) => path.join(coreDir, name);
  return {
    name: 'copy-ffmpeg-core',
    // Dev has no dist to copy into: hand the files straight off disk instead.
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const name = files.find((f) => req.url?.startsWith(`/ffmpeg/${f}`));
        if (!name) return next();
        res.setHeader(
          'Content-Type',
          name.endsWith('.wasm') ? 'application/wasm' : 'text/javascript',
        );
        // Announce the size so the download reports real progress in dev too,
        // instead of an indeterminate bar the production build does not have.
        res.setHeader('Content-Length', fs.statSync(sourceOf(name)).size);
        fs.createReadStream(sourceOf(name)).pipe(res);
      });
    },
    buildStart() {
      // Fail the build rather than ship a dist whose /ffmpeg/ 404s at runtime.
      for (const name of files) {
        if (!fs.existsSync(sourceOf(name))) {
          this.error(`@ffmpeg/core is missing ${name} at ${coreDir}. Run npm install.`);
        }
      }
    },
    async writeBundle(options) {
      const outDir = options.dir ?? 'dist';
      await fs.promises.mkdir(path.join(outDir, 'ffmpeg'), { recursive: true });
      for (const name of files) {
        await fs.promises.copyFile(sourceOf(name), path.join(outDir, 'ffmpeg', name));
      }
    },
  };
}

// The site is served from the root of the custom domain
// (https://selfcut.alegzandr.com). Set VITE_BASE to override.
const BASE_PATH = process.env.VITE_BASE ?? '/';

export default defineConfig({
  base: BASE_PATH,
  // Static landing pages (one per language, generated by
  // scripts/build-landing.mjs) and the editor SPA at /app/.
  appType: 'mpa',
  plugins: [react(), tailwindcss(), injectCsp(), copyFFmpegCore()],
  worker: {
    format: 'es',
  },
  optimizeDeps: {
    // ffmpeg.wasm locates its worker with `new URL('./worker.js', import.meta.url)`.
    // Dep pre-bundling flattens the package into a single chunk, so that URL points
    // at a file that no longer exists and the worker 404s (dev only, silently).
    exclude: ['@ffmpeg/ffmpeg', '@ffmpeg/util'],
  },
  build: {
    target: 'es2022',
    rollupOptions: {
      input: {
        landing: 'index.html',
        'landing-en': 'en/index.html',
        'landing-es': 'es/index.html',
        'landing-de': 'de/index.html',
        'landing-pt-br': 'pt-BR/index.html',
        app: 'app/index.html',
      },
    },
  },
});
